apiVersion: v1
kind: Namespace
metadata:
  name: fabrik-oa
  labels:
    dynatrace.com/inject: "true"
    dynatrace.com/enrich: "true"
  annotations:
    dynatrace.com/log-monitoring: "true"
---
apiVersion: v1
kind: Namespace
metadata:
  name: fabrik-ot
  labels:
    dynatrace.com/inject: "false"
    dynatrace.com/enrich: "true"
  annotations:
    dynatrace.com/log-monitoring: "false"
